/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceberRouteImport } from './routes/receber'
import { Route as PagarRouteImport } from './routes/pagar'
import { Route as IndexRouteImport } from './routes/index'

const ReceberRoute = ReceberRouteImport.update({
  id: '/receber',
  path: '/receber',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarRoute = PagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagar': typeof PagarRoute
  '/receber': typeof ReceberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagar': typeof PagarRoute
  '/receber': typeof ReceberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pagar': typeof PagarRoute
  '/receber': typeof ReceberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pagar' | '/receber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pagar' | '/receber'
  id: '__root__' | '/' | '/pagar' | '/receber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagarRoute: typeof PagarRoute
  ReceberRoute: typeof ReceberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receber': {
      id: '/receber'
      path: '/receber'
      fullPath: '/receber'
      preLoaderRoute: typeof ReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar': {
      id: '/pagar'
      path: '/pagar'
      fullPath: '/pagar'
      preLoaderRoute: typeof PagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagarRoute: PagarRoute,
  ReceberRoute: ReceberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
